import { Platform, StyleSheet } from "react-native";
import { PINGME_COLORS } from "@/constants/theme";

export const COLORS = PINGME_COLORS;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bgWhite,
  },

  // ── MAP ──
  map: {
    ...StyleSheet.absoluteFillObject,
    marginBottom: -40,
  },

  // ── TOP BAR ──
  topBarContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    zIndex: 10,
  },
  topRoundBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.bgGlass,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 8,
  },
  notiDot: {
    position: "absolute",
    top: 6,
    right: 6,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: COLORS.danger,
    borderWidth: 1.5,
    borderColor: COLORS.bgWhite,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 3,
  },

  // ── SEARCH HERO OVERLAY ──
  searchOverlayBackground: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255, 255, 255, 0.85)", // Glassmorphism backdrop
    zIndex: 40,
  },
  heroSearchContainer: {
    position: "absolute",
    height: 48,
    backgroundColor: COLORS.bgGlass,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 10,
    zIndex: 50,
    overflow: "hidden", // Important for hiding input when button
  },
  heroSearchExpanded: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  heroSearchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 15,
    color: COLORS.textPrimary,
    fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
    ...(Platform.OS === "web" ? ({ outlineStyle: "none" } as any) : {}),
  },
  nearbyListContainer: {
    position: "absolute",
    backgroundColor: COLORS.bgWhite,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 12,
    zIndex: 45,
    maxHeight: 400,
  },
  nearbyTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: COLORS.primary,
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  emptyNearby: {
    color: COLORS.textSecondary,
    fontSize: 14,
    fontStyle: "italic",
    textAlign: "center",
    paddingVertical: 10,
  },
  nearbyItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  nearbyAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: COLORS.primary,
  },
  nearbyInfo: {
    flex: 1,
    marginLeft: 12,
  },
  nearbyName: {
    color: COLORS.textPrimary,
    fontSize: 15,
    fontWeight: "700",
  },
  nearbyDistance: {
    color: COLORS.textSecondary,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 2,
  },
  nearbyChatBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.bgMid,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
  },

  // ── FLOATING CHAT BUTTON ──
  floatingBtnWrapper: {
    position: "absolute",
    zIndex: 10,
  },
  chatBtn: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: COLORS.secondary,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: COLORS.bgWhite,
    shadowColor: COLORS.secondary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 12,
  },
  chatBadge: {
    position: "absolute",
    top: -2,
    right: -2,
    backgroundColor: COLORS.danger,
    width: 22,
    height: 22,
    borderRadius: 11,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: COLORS.bgWhite,
  },
  chatBadgeText: {
    color: COLORS.white,
    fontSize: 11,
    fontWeight: "bold",
  },

  // ── FRIEND MARKER ──
  friendMarker: {
    alignItems: "center",
  },
  friendAvatarWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2.5,
    borderColor: COLORS.primary,
    overflow: "hidden",
    backgroundColor: COLORS.bgWhite,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },
  friendAvatarWrapperOffline: {
    borderColor: COLORS.offline,
  },
  friendAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  friendAvatarText: {
    color: COLORS.primary,
    fontSize: 18,
    fontWeight: "bold",
  },
  onlineDot: {
    position: "absolute",
    bottom: -1,
    right: -1,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: COLORS.online,
    borderWidth: 2,
    borderColor: COLORS.bgWhite,
  },

  // ── MY LOCATION RADAR MARKER ──
  myMarkerContainer: {
    width: 160,
    height: 160,
    justifyContent: "center",
    alignItems: "center",
    overflow: "visible",
  },
  myAvatarRing: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 3,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.bgWhite,
    padding: 2,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  myAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
  },
  myAvatarFallback: {
    backgroundColor: COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  myAvatarText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: "900",
  },

  // ── FRIEND POPUP CARD ──
  popupOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    padding: 16,
  },
  popupCard: {
    backgroundColor: COLORS.bgWhite,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    shadowColor: COLORS.textPrimary,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
    elevation: 16,
  },
  popupHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  popupAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  popupAvatarPlaceholder: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 2,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.bgMid,
    justifyContent: "center",
    alignItems: "center",
  },
  popupAvatarText: {
    color: COLORS.primary,
    fontSize: 22,
    fontWeight: "bold",
  },
  popupInfo: {
    marginLeft: 14,
    flex: 1,
  },
  popupName: {
    color: COLORS.textPrimary,
    fontSize: 18,
    fontWeight: "bold",
  },
  popupStatus: {
    color: COLORS.online,
    fontSize: 12,
    fontWeight: "700",
    marginTop: 3,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  popupStatusOffline: {
    color: COLORS.textSecondary,
  },
  popupClose: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.bgMid,
    justifyContent: "center",
    alignItems: "center",
  },
  popupDetails: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: COLORS.border,
  },
  popupDetailItem: {
    alignItems: "center",
  },
  popupDetailLabel: {
    color: COLORS.textSecondary,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: 2,
    fontWeight: "600",
  },
  popupDetailValue: {
    color: COLORS.textPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  popupActions: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingTop: 8,
  },
  popupActionBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.bgMid,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  popupActionBtnPrimary: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  popupActionText: {
    color: COLORS.textPrimary,
    fontSize: 14,
    fontWeight: "700",
    marginLeft: 6,
  },
  popupActionTextPrimary: {
    color: COLORS.white,
  },

  // ── LOADING STATE ──
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: COLORS.bgWhite,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 50,
  },
  loadingText: {
    color: COLORS.primary,
    fontSize: 14,
    fontWeight: "700",
    marginTop: 16,
    letterSpacing: 1,
  },
});
